---

# Some versions store the inputs field as string in the database
# In those cases, we need to convert it in order to be able to process
- name: Convert input from string if needed
  set_fact:
    inputs: >-
      {{ (outer.inputs|from_json) if outer.inputs is string else outer.inputs }}

- name: Decrypt password for '{{ outer.name }}'
  command: >
    docker run
    -e "AWX_SECRET_KEY={{ awx_credentials['db']['secret'] }}"
    -e "AWX_NAME={{ outer.name }}"
    -e "AWX_FIELD={{ item.key }}"
    -e "AWX_PASSWORD={{ item.value }}"
    -e "AWX_PK={{ outer.id | int }}"
    --rm awx_decrypt:latest /tmp/decrypt.py
  loop: "{{ inputs | dict2items }}"
  loop_control:
    label:
      - "{{ item.key }}"
  vars:
    awx_id: "{{ outer.id }}"
  register: _pwd
  changed_when: false
  ignore_errors: true
  when: item.value is search('^\$')
  become: no
  delegate_to: localhost

- name: Append to combined list
  set_fact:
    pwd_list: "{{ pwd_list|default([]) + [ (item.stdout|from_json) ] }}"
  loop: "{{ _pwd.results }}"
  loop_control:
    label:
      - "{{ item.item.key }}"
  when: item.stdout is defined
