---

# ---------------------------------------------------------
# Install requirements
# ---------------------------------------------------------

- name: Install postgresql client
  ansible.builtin.package:
    name: postgresql
  become: yes
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int >= 8

- name: Install pypi packages (awxkit/pexpect)
  ansible.builtin.pip:
    name:
      - awxkit=={{ awx_credentials_awxkit }}
      - pexpect
    executable: pip3
  become: yes

# ---------------------------------------------------------
# Retrieve credential information (no secrets)
# ---------------------------------------------------------

- name: Get overview of all credentials
  ansible.builtin.command: >-
    {{ awx_credentials_cmd }} credentials list --all
  environment:
    TOWER_HOST: "{{ awx_credentials['api']['url'] }}"
    TOWER_USERNAME: "{{ awx_credentials['api']['user'] }}"
    TOWER_PASSWORD: "{{ awx_credentials['api']['password'] }}"
    TOWER_VERIFY_SSL: "{{ awx_credentials['api']['validate_certs'] }}"
  changed_when: false
  ignore_errors: true
  register: _awx_credentials
  # delegate_to: awx_decrypt

# ---------------------------------------------------------
# Retrieve credential secrets
# ---------------------------------------------------------

- name: Perform query for all credentials  # noqa no-free-form
  ansible.builtin.command: >-
    psql --host={{ awx_credentials['db']['host'] }}
         --port={{ awx_credentials['db']['port'] }}
         --dbname={{ awx_credentials['db']['name'] }}
         --username={{ awx_credentials['db']['user'] }}
         --command="copy (select * from main_credential) To STDOUT With CSV DELIMITER ',' HEADER;"
  changed_when: false
  register: _psql_csv
  environment:
    PGPASSWORD: "{{ awx_credentials['db']['password'] }}"
    PATH: "{{ ansible_env.PATH }}:/opt/rh/rh-postgresql10/root/usr/bin"
    LD_LIBRARY_PATH: "{{ ansible_env.PATH }}:/opt/rh/rh-postgresql10/root/usr/lib64"
    LIBRARY_PATH: "{{ ansible_env.PATH }}:/opt/rh/rh-postgresql10/root/usr/lib64"

- name: Create tempfile
  ansible.builtin.tempfile:
  changed_when: false
  register: _tempfile

- name: Write query results to csv file
  ansible.builtin.copy:
    content: "{{ _psql_csv.stdout }}"
    dest: "{{ _tempfile.path }}"
    mode: "0600"
  changed_when: false

- name: Read csvfile into ansible
  community.general.read_csv:
    path: "{{ _tempfile.path }}"
  register: creds

- name: Delete temporary csv file
  ansible.builtin.file:
    path: "{{ _tempfile.path }}"
    state: absent
  changed_when: false


# ---------------------------------------------------------
# Process & write credential data
# ---------------------------------------------------------

- name: Create output location {{ awx_credentials_dest }}
  ansible.builtin.file:
    path: "{{ awx_credentials_dest }}"
    state: directory
    mode: "0700"
  delegate_to: localhost
  become: no

- name: Decrypt all crypted values
  ansible.builtin.include_tasks:
    file: decrypt.yml
    apply:
      delegate_to: awx_decrypt
  loop: "{{ creds.list }}"
  loop_control:
    loop_var: outer
    label:
      - "{{ outer.name }}"

- name: Write credential information to file
  ansible.builtin.copy:
    content: "{{ _awx_credentials.stdout | from_json | json_query('results') | to_nice_json }}"
    dest: "{{ awx_credentials_dest }}/credential-export.json"
    mode: "0600"
  delegate_to: localhost
  connection: local

- name: Write credential secrets to file
  ansible.builtin.copy:
    content: "{{ awx_credentials_list | to_nice_json }}"
    dest: "{{ awx_credentials_dest }}/credential-secrets.json"
    mode: '0600'
  delegate_to: localhost
  become: no

- name: Encrypt credentials
  when: awx_credentials_vault_pass is defined
  delegate_to: localhost
  connection: local
  become: no
  block:

    - name: Encrypt the file
      ansible.builtin.expect:
        command: ansible-vault encrypt --ask-vault-pass --encrypt-vault-id {{ awx_credentials_vault_id }} {{ awx_credentials_dest }}/credential-secrets.json
        responses:
          New Vault password: "{{ awx_credentials_vault_pass }}"
          Confirm New Vault password: "{{ awx_credentials_vault_pass }}"

  rescue:

    - name: Delete unencrypted file
      ansible.builtin.file:
        path: "{{ awx_credentials_dest }}/credential-secrets.json"
        state: absent
