---

- name: Construct credential export name
  set_fact:
    credential_export: "{{ awx_import_path }}/credential-export.json"
    credential_secrets: "{{ awx_import_path }}/credential-secrets.json"

- name: Load JSON from disk
  set_fact:
    credential_export:  "{{ lookup('file', credential_export) | from_json }}"
    credential_secrets: "{{ lookup('file', credential_secrets) | from_json }}"

- name: Convert list w/ passwords into dict
  set_fact:
    pwd_dict1: "{{ ( pwd_dict1|default({}) ) | combine({ (item.id|string): { 'inputs': { item.field: item.password }} }, recursive=True ) }}"
  loop: "{{ credential_secrets }}"
  loop_control:
    label:
      - "{{ item.id }}"
      - "{{ item.field }}"

- name: Create simplified dict with all inputs
  set_fact:
    pwd_dict2: >-
      {{ ( pwd_dict2|default({}) ) | combine({ (item.id|string): { 'name': item.name, 'type': item.summary_fields.credential_type.name, 'inputs': item.inputs }}, recursive=True) }}
  loop: "{{ credential_export }}"
  loop_control:
    label:
      - "{{ item.id }}"

- name: Merge both dicts
  set_fact:
    pwd_dict: "{{ pwd_dict2 | combine(pwd_dict1, recursive=True) }}"

- name: Add all secrets to existing credentials
  awx.awx.credential:
    controller_host: https://127.0.0.1
    controller_username: "{{ tower_awx[awx_type][awx_env]['api_user'] }}"
    controller_password: "{{ tower_awx[awx_type][awx_env]['api_password'] }}"
    validate_certs: False
    name: "{{ item.name }}"
    credential_type: "{{ pwd_dict[(item.id|string)]['type'] }}"
    inputs: "{{ pwd_dict[(item.id|string)]['inputs'] }}"
  loop: "{{ credential_export }}"
  loop_control:
    label:
      - "{{ item.id }}"
      - "{{ item.name }}"
