---

- name: Construct credential export name
  ansible.builtin.set_fact:
    credential_export: "{{ awx_import_path }}/credential-export.json"
    credential_secrets_json: "{{ awx_import_path }}/credential-secrets.json"
    credential_secrets_gpg: "{{ awx_import_path }}/credential-secrets.json.gpg"

- name: Decrypt secrets  # noqa no-changed-when no-free-form
  ansible.builtin.shell: |
    umask 077
    pass=$(mktemp)
    echo "{{ awx_credentials_vault_pass }}" > $pass
    gpg -q --batch --yes --passphrase-file $pass --decrypt --output {{ credential_secrets_json }} {{ credential_secrets_gpg }}
    shred -n 3 -z -u $pass
  no_log: true

- name: Load JSON from disk
  ansible.builtin.set_fact:
    credential_export: "{{ lookup('file', credential_export) | from_json }}"
    credential_secrets: "{{ lookup('file', credential_secrets_json) | from_json }}"

- name: Delete unencrypted credentials from disk
  ansible.builtin.command:
    cmd: shred -n 3 -z -u {{ credential_secrets_json }}
  changed_when: false

- name: Convert list w/ passwords into dict  # noqa jinja[spacing]
  ansible.builtin.set_fact:
    pwd_dict1: >-
      {{ (pwd_dict1 | default({})) |
      combine({ (item.id | string): { 'inputs': { item.field: item.password }} }, recursive=True ) }}
  loop: "{{ credential_secrets }}"
  loop_control:
    label:
      - "{{ item.id }}"
      - "{{ item.field }}"

- name: Create simplified dict with all inputs  # noqa jinja[spacing]
  ansible.builtin.set_fact:
    pwd_dict2: >-
      {{ (pwd_dict2 | default({})) |
      combine({ (item.id | string): { 'name': item.name,
                                      'organization': item.summary_fields.organization.name,
                                      'description': item.description,
                                      'type': item.summary_fields.credential_type.name,
                                      'inputs': item.inputs
                                    }
              }, recursive=True) }}
  loop: "{{ credential_export }}"
  loop_control:
    label:
      - "{{ item.id }}"

- name: Merge both dicts
  ansible.builtin.set_fact:
    pwd_dict: "{{ pwd_dict2 | combine(pwd_dict1, recursive=True) }}"

- name: Add all secrets to existing credentials
  awx.awx.credential:
    controller_host: "{{ awx_credentials['api']['url'] }}"
    controller_username: "{{ awx_credentials['api']['user'] }}"
    controller_password: "{{ awx_credentials['api']['password'] }}"
    validate_certs: "{{ awx_credentials['api']['validate_certs'] }}"
    name: "{{ item.name }}"
    description: "{{ pwd_dict[(item.id | string)]['description'] }}"
    credential_type: "{{ pwd_dict[(item.id | string)]['type'] }}"
    organization: "{{ pwd_dict[(item.id | string)]['organization'] }}"
    inputs: "{{ pwd_dict[(item.id | string)]['inputs'] }}"
    update_secrets: "{{ awx_credentials_update_secrets }}"
  loop: "{{ credential_export }}"
  loop_control:
    label:
      - "{{ item.id }}"
      - "{{ item.name }}"
