---

- name: Assertions
  assert:
    that:
      - awx_credentials_dest_root
      - awx_credentials_identifier

- name: Define output location
  set_fact:
    awx_credentials_dest: >-
      {{ awx_credentials_dest_root }}/{{ awx_credentials_identifier }}

- name: Show output location
  debug: var=awx_credentials_dest

- include_tasks: docker.yml

- include_tasks: export.yml
  when:
    - awx_credentials_mode is defined
    - awx_credentials_mode == 'export'

- include_tasks: import.yml
  when:
    - awx_credentials_mode is defined
    - awx_credentials_mode == 'import'
