---

- name: Assertions
  ansible.builtin.assert:
    that:
      - awx_credentials_dest_root is defined
      - awx_credentials_identifier is defined

- name: Define output location
  ansible.builtin.set_fact:
    awx_credentials_dest: >-
      {{ awx_credentials_dest_root }}/{{ awx_credentials_identifier }}

- name: Show output location
  ansible.builtin.debug:
    var: awx_credentials_dest

- name: Setup temporary docker container
  ansible.builtin.include_tasks:
    file: docker.yml
    apply:
      run_once: yes
      become: no
      delegate_to: localhost
  when:
    - awx_credentials_docker | bool
    - awx_credentials_mode == 'export'

- name: Include export.yml
  ansible.builtin.include_tasks: export.yml
  when:
    - awx_credentials_mode is defined
    - awx_credentials_mode == 'export'

- name: Include import.yml
  ansible.builtin.include_tasks: import.yml
  when:
    - awx_credentials_mode is defined
    - awx_credentials_mode == 'import'
