---

- name: Install postgresql client
  ansible.builtin.package:
    name: postgresql
  become: yes
  when:
    - ansible_facts.os_family == 'RedHat'
    - ansible_facts.distribution_major_version | int >= 8
