---

- import_playbook: converge-pre.yml

- name: Converge
  hosts: all
  vars:
    awx_credentials_identifier: awx-1
    awx_credentials_dest_root: /tmp/xxx
  tasks:
    - name: Include role 'ansible-role-awx_credentials'
      include_role:
        name: ansible-role-awx_credentials
