---

# AWX Credentials
- hosts: all
  vars_files:
    - vars.yml
  tasks:

    - name: Pause play until a URL is reachable from this host
      uri:
        url: "{{ awx_credentials['api']['url'] }}"
        validate_certs: "{{ awx_credentials['api']['validate_certs'] }}"
        follow_redirects: yes
        method: GET
      register: _result
      until: _result.status == 200
      retries: 30
      delay: 10

    - name: Install awxkit
      pip:
        name: awxkit=={{ awx_credentials_awxkit }}
        state: present

    - name: Create all organizations
      awx.awx.organization:
        controller_host: "{{ awx_credentials['api']['url'] }}"
        controller_username: "{{ awx_credentials['api']['user'] }}"
        controller_password: "{{ awx_credentials['api']['password'] }}"
        validate_certs: "{{ awx_credentials['api']['validate_certs'] }}"
        name: "{{ item.name }}"
      loop: "{{ awx_resources.organizations }}"
      loop_control:
        label:
          - "{{ item.name }}"

    - name: Create all credentials
      awx.awx.credential:
        controller_host: "{{ awx_credentials['api']['url'] }}"
        controller_username: "{{ awx_credentials['api']['user'] }}"
        controller_password: "{{ awx_credentials['api']['password'] }}"
        validate_certs: "{{ awx_credentials['api']['validate_certs'] }}"
        name: "{{ item.name }}"
        organization: "{{ item.organization }}"
        credential_type: "{{ item.credential_type }}"
        inputs: "{{ item.inputs }}"
      loop: "{{ awx_resources.credentials }}"
      loop_control:
        label:
          - "{{ item.name }}"
      tags: molecule-idempotence-notest
