FROM rockylinux:8

COPY decrypt.py /tmp/decrypt.py

RUN \
{% if proxy_url is defined and proxy_url | length > 0 %}
    export HTTPS_PROXY={{ proxy_url }} && \
    export HTTP_PROXY={{ proxy_url }} && \
    export https_proxy={{ proxy_url }} && \
    export http_proxy={{ proxy_url }} && \
{% endif %}
    dnf update -y && \
    dnf -y install iproute openssh && \
    dnf -y install python3.11 python3-pip python3-psycopg2 python3-cryptography && \
    dnf -y install postgresql && \
    mkdir -p /usr/local/venv/awxkit && \
    python3.11 -m venv /usr/local/venv/awxkit && \
    /usr/local/venv/awxkit/bin/pip3 install pip wheel "setuptools<81" --upgrade && \
    /usr/local/venv/awxkit/bin/pip3 install awxkit=={{ awx_credentials_awxkit }} && \
    ln -s /usr/local/venv/awxkit/bin/awx /usr/local/bin/awx

ENTRYPOINT ["tail", "-f", "/dev/null"]
