FROM rockylinux:8

COPY decrypt.py /tmp/decrypt.py

RUN \
{% if proxy_url is defined and proxy_url | length > 0 %}
    export HTTPS_PROXY={{ proxy_url }} && \
    export HTTP_PROXY={{ proxy_url }} && \
    export https_proxy={{ proxy_url }} && \
    export http_proxy={{ proxy_url }} && \
{% endif %}
    dnf update -y && \
    dnf -y install iproute openssh && \
    dnf -y install python2 python2-pip python2-psycopg2 && \
    dnf -y install python3 python3-pip python3-psycopg2 python3-cryptography && \
    dnf -y install postgresql && \
    pip2 install cryptography && \
    pip3 install awxkit=={{ awx_credentials_awxkit }}

ENTRYPOINT ["tail", "-f", "/dev/null"]
